spring:
  application:
    name: project-PS-email
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: 97822562298b59
    password: 8dadc0bb931515
  activemq:
    broker-url: tcp://localhost:61616
server:
  port: 8888
  servlet:
    context-path: '/api'
  error:
    whitelabel:
      enabled: false
queues:
  async-mail-sender-request: async-mail-sender-request